apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xh6it5f8g-java-quarkus
  janus-idp.io/tekton: xh6it5f8g-java-quarkus
  backstage.io/kubernetes-id: xh6it5f8g-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xh6it5f8g-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
